///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/balkan.aks
/// Generation time: Fri Nov  3 16:20:19 CET 2023
///

/// Song 'mercadona' metadata macros
#define mercadona_address  0x0040
#define mercadona_size     1539
#define mercadona_end      0x642

/// Song 'mercadona' array declaration
extern void mercadona[mercadona_size];
