///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/kavalsviri.aks
/// Generation time: Fri Nov  3 16:20:18 CET 2023
///

/// Song 'kavalsviri' metadata macros
#define kavalsviri_address  0x0700
#define kavalsviri_size     923
#define kavalsviri_end      0xa9a

/// Song 'kavalsviri' array declaration
extern void kavalsviri[kavalsviri_size];
