///
/// File generated by cpct_aks2c CPCtelera script
/// Souce file of this conversion: assets/music/sfxsong.aks
/// Generation time: Fri Nov  3 16:20:18 CET 2023
///

/// Song 'sfx' metadata macros
#define sfx_address  0x0AA0
#define sfx_size     101
#define sfx_end      0xb04

/// Song 'sfx' array declaration
extern void sfx[sfx_size];
